title: dan.osbornes.website
description: "Music, Tech, and Travels."
url: dan.osbornes.website
email: dan@osbornes.website
author: Dan Osborne
twitter_username: ozdanborne
github_username: ozdanborne
twitter:
  username: ozdanborne

permalink: /:categories/:title
url: https://dan.osbornes.website
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

google-analytics: UA-38671231-2
